version: '3.7'

services:
  pokerfoci-auth:
    image: dezsovargadev/pokerfoci-auth:0.0.1-SNAPSHOT
      #build:
      #context: .
    #dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always
    depends_on: # Start the depends_on first
      - mysql
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql:3306/pokerfoci_auth",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: pokerfoci
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: pokerfoci_auth
    volumes:
      - mysql-database-data-volume:/var/lib/mysql

# Volumes
volumes:
  mysql-database-data-volume: