apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: pokerfoci-auth
  name: pokerfoci-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pokerfoci-auth
  template:
    metadata:
      labels:
        io.kompose.network/pof-default: "true"
        io.kompose.service: pokerfoci-auth
    spec:
      containers:
        - env:
            - name: RDS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: RDS_DB_NAME
                  name: pokerfoci-config
            - name: RDS_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: RDS_HOSTNAME
                  name: pokerfoci-config
            - name: RDS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: RDS_PASSWORD
                  name: pokerfoci-secrets
            - name: RDS_PORT
              valueFrom:
                configMapKeyRef:
                  key: RDS_PORT
                  name: pokerfoci-config
            - name: RDS_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: RDS_USERNAME
                  name: pokerfoci-config
            - name: POKERFOCI_UI_CROSS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  key: POKERFOCI_UI_CROSS_ORIGIN
                  name: pokerfoci-config
          image: dezsovargadev/pokerfoci-auth:0.0.2-SNAPSHOT
          name: pokerfoci-auth
          ports:
            - containerPort: 8081
      restartPolicy: Always
