apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: pokerfoci-auth
  name: pokerfoci-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pokerfoci-auth
  template:
    metadata:
      labels:
        io.kompose.network/pof-default: "true"
        io.kompose.service: pokerfoci-auth
    spec:
      containers:
        - env:
            - name: RDS_DB_NAME
              value: pokerfoci_auth
            - name: RDS_HOSTNAME
              value: mysql
            - name: RDS_PASSWORD
              value: root
            - name: RDS_PORT
              value: "3306"
            - name: RDS_USERNAME
              value: root
            - name: POKERFOCI_UI_CROSS_ORIGIN
              value: "http://34.72.39.154:3000"
          image: dezsovargadev/pokerfoci-auth:0.0.1-SNAPSHOT
          name: pokerfoci-auth
          ports:
            - containerPort: 8081
      restartPolicy: Always
